### ISSUE TITLE
Upgrade to hapi8

### ISSUE THREAD

**Issue by devinivy** [smaxwellstewart/hapi-dash#11]
I realize there may be little impetus to do this, but I figured I'd make an issue to get hapi up-to-date, especially with hapi9 coming-out before long!

**Comment by smaxwellstewart** [comment]
Hey sorry in the delay in responding, lots of stuff keeping me busy! Also I wanted to give some thought to the direction of this project.

Soooo the good news is I am looking to upgrade this in the not too distant future, but with it being both a full stack I am taking the time to revisit frameworks and have a major refactor. I'm thinking about implementing Angular 2 and also have a re-write of some of the hapi parts.

I will in the meantime be accepting pull requests if the community has any improvements they can't wait for.

**Comment by smaxwellstewart** [comment]
@devinivy So the good news is I have actively started a new up-to-date dashboard. It will be a little different as it will be a service for CRUD and authenticating users, but fundamentally it will be very similar to this repo. It will be:

- Same awesome free theme.
- Very similar stack but little different stack, Hapi 9, Mongodb 3, Mongoose for db models and Angular 1.8 for.
- 100 % Code coverage of Unit tests
- Integration Tests
- Herokku / Dokku deployable

**Comment by smaxwellstewart** [comment]
For anybody eager to preview:

[https://github.com/smaxwellstewart/user-microservice](https://github.com/smaxwellstewart/user-microservice)

**Comment by devinivy** [comment]
Thanks for the update!  Feel free to close this, unless you'd rather not :)
