### ISSUE TITLE
can't start success

### ISSUE THREAD

**Issue by jonahzheng** [smaxwellstewart/hapi-dash#13]
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

**Comment by smaxwellstewart** [comment]
@jonahzheng I am in the process of updating all the packages. I am now changing some code that is incompatible with new versions. Hopefully I will have a fix soon!

**Comment by jonahzheng** [comment]
@smaxwellstewart  thank you！
other error
js-bson: Failed to load c++ bson extension, using pure JS version 

about this error
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
solution is:
modity
node_modules\mongodb\node_modules\bson\ext\index.js bson = require('../build/Release/bson')  change to bson = require('bson')

**Comment by smaxwellstewart** [comment]
@jonahzheng Just got the API server working. Hopefully will get the GUI
server done soon!
